import type {Metadata} from "next";
import {Comfortaa, Nunito_Sans} from "next/font/google";
import {NextUIProvider} from "@nextui-org/react";
import "./globals.css";
import Menu from "@/app/components/menu/menu";

const comfortaa = Comfortaa({
    subsets: ["latin"],
    variable: '--font-comfortaa',
});

const nunitoSans = Nunito_Sans({
    subsets: ["latin"],
    variable: '--font-nunito_sans',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${nunitoSans.className} ${comfortaa.variable} ${nunitoSans.variable}`}>
        <NextUIProvider>
            <Menu></Menu>
            {children}
        </NextUIProvider>
        </body>
        </html>
    );
}
